services:
  db:
    image: postgres:14-alpine
    hostname: db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 15s
      retries: 5
      start_period: 3s
    environment:
      POSTGRES_DB: sge2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - /opt/sge2/data:/var/lib/postgresql/data
      - /opt/sge2/pg_dump.sql:/docker-entrypoint-initdb.d/pg_dump.sql
    networks:
      - sge2

  app:
    image: registry.frba.utn.edu.ar/ext/sge2
    env_file:
      - /opt/sge2/.env
    hostname: app
    networks:
      - sge2
    depends_on:
      db:
        condition: service_healthy

  proxy:
    image: nginx:1.27-alpine
    volumes:
      - /opt/sge2/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    networks:
      - sge2
    depends_on:
      - app

networks:
  sge2:

volumes:
  sge2-db-data:
